Add convenience functions to remove build images and containers
Kopano-dev/kopano-docker pull request #11
Opened 2020-01-24 15:39 UTC by h44z

2020-01-24 22:12 UTC, fbartels commented
The clean all images does not actually remove all images:

```
$ docker images --format '{{.Repository}}:{{.Tag}}' | grep 'fbartels/kopano_'
fbartels/kopano_base:<none>
```
from a quick search there does not really to really delete all these images in a single command.

What I am using when I want to clean out my local system is `docker system prune -a`

2020-01-27 18:07 UTC, h44z commented
Hm, is the base image used in any container? If I try this call, all build images get deleted.

2020-01-27 19:46 UTC, fbartels commented
Yes, kopano_base is included as the base for for kopano_core, kopano_php, kopno_zpush, .. basically everything Debian based.

It feels like Docker just occasionally creates these dangling images. Pruning my system and then running `make build-all` already creates this:

```
$ docker image ls --filter dangling=true
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              dedb46d1f03d        11 minutes ago      22.8MB
<none>              <none>              7b56fd2a2d73        15 minutes ago      376MB
```

But at least none with the "none" tag.

2020-01-29 20:00 UTC, fbartels requested changes
I think with the inline change it would be good to merge

2020-01-29 20:00 UTC, fbartels commented on Makefile
> +	docker rmi $$(docker images --format '{{.Repository}}:{{.Tag}}' | grep '${docker_repo}/kopano_')
adding a `| grep -v '<none>'` will skip all items with the tag that cannot be deleted

2020-01-30 11:25 UTC, merged

2020-01-30 11:26 UTC, fbartels commented
Thanks!